# Generated by Django 2.2 on 2019-06-15 00:44

import articles.models
from django.db import migrations, models
#import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                #('authors', djongo.models.fields.ArrayModelField(model_container=articles.models.Author)),
                ('publisher', models.TextField()),
                ('journal', models.TextField()),
                ('datepublished', models.DateField()),
                ('source_link', models.URLField()),
                ('isopenaccess', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
